import mongoose, { Schema, model } from 'mongoose'; // Import Mongoose and the types needed for schema creation

interface IResumeReport {
  jobDescription: string; // Text of the job description used for the resume review
  resumeText: string; // Full resume content provided by the user
  selfDescription: string; // User's self-description or summary section

  overallScore: {
    score: number; // Numeric score representing overall resume quality
  };

  technicalQuestions: {
    question: string; // Technical interview question generated by the report
    intention: string; // Why the question is asked or what it evaluates
    answer: string; // Recommended answer or evaluation text
  }[]; // Array of technical question objects

  behavioralQuestions: {
    question: string; // Behavioral interview question generated by the report
    intention: string; // The intent behind the behavioral question
    answer: string; // Recommended answer or evaluation text
  }[]; // Array of behavioral question objects

  skillsGaps: {
    skill: string; // Skill the resume is missing or needs improvement
    severity: 'low' | 'medium' | 'high'; // Severity level of the gap
  }[]; // Array of skill gap objects

  preparationPlan: {
    day: number; // Day number in the preparation plan
    resources: string[]; // Learning resources or links for that day
    focusAreas: string[]; // Topics to focus on for that day
    tasks: string[]; // Action items or practice tasks for that day
  }[]; // Array of preparation plan entries
}

const resumeReportSchema = new Schema<IResumeReport>(
  {
    jobDescription: { type: String, required: [true, "Job description is required"] }, // Required job description text
    resumeText: { type: String }, // Resume text is optional but recommended
    selfDescription: { type: String }, // Optional self-description text
    overallScore: {
      score: { type: Number, required: true, min: [0, "Score must be at least 0"], max: [100, "Score cannot exceed 100"] }, // Score must be between 0 and 100
    },
    technicalQuestions: [
      {
        question: { type: String, required: true }, // Required technical question text
        intention: { type: String, required: true }, // Required explanation of the question intent
        answer: { type: String, required: true }, // Required answer or guidance text
      },
    ],
    behavioralQuestions: [
      {
        question: { type: String, required: true }, // Required behavioral question text
        intention: { type: String, required: true }, // Required explanation of the question intent
        answer: { type: String, required: true }, // Required answer or guidance text
      },
    ],
    skillsGaps: [
      {
        skill: { type: String, required: true }, // Required name of the missing or weak skill
        severity: {
          type: String, // Severity stored as a string
          required: true, // Severity is required
          enum: ['low', 'medium', 'high'], // Allowed severity values
        },
      },
    ],
    preparationPlan: [
      {
        day: { type: Number, required: true }, // Day index for plan entry
        resources: { type: [String], required: true }, // Required list of resource strings
        focusAreas: { type: [String], required: true }, // Required focus area names
        tasks: { type: [String], required: true }, // Required list of tasks
      },
    ],
  },
  { timestamps: true } // Automatically add createdAt and updatedAt fields
);

export const resumeReportModel = model<IResumeReport>('ResumeReport', resumeReportSchema); // Export the model for use in the app

/*
Example data shape expected by the ResumeReport model:
{
  jobDescription: "Frontend developer role focused on React and TypeScript",
  resumeText: "Experienced developer with 5 years building web apps...",
  selfDescription: "I build user-friendly interfaces and enjoy solving UI problems.",
  overallScore: {
    score: 85,
  },
  technicalQuestions: [
    {
      question: "How would you optimize React rendering performance?",
      intention: "Assess knowledge of React rendering and memoization.",
      answer: "Use memo, useCallback, and key props carefully to reduce unnecessary re-renders.",
    },
  ],
  behavioralQuestions: [
    {
      question: "Tell me about a time you handled a tight deadline.",
      intention: "Assess communication and time-management skills.",
      answer: "I prioritized features, communicated risks, and delivered a minimum viable product on time.",
    },
  ],
  skillsGaps: [
    {
      skill: "Unit testing",
      severity: "medium",
    },
  ],
  preparationPlan: [
    {
      day: 1,
      resources: ["https://react.dev/docs/getting-started", "https://typescriptlang.org/docs/"],
      focusAreas: ["React hooks", "TypeScript types"],
      tasks: ["Build a small React component", "Add TypeScript interfaces"],
    },
  ],
}
*/
